default: &default
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  adapter: mysql2
  username: root
  password:password: "mokamoka8410"
  host: localhost
  database: furima-46486_development

test:
  <<: *default
  adapter: mysql2
  username: root
  password:password: "mokamoka8410"
  host: localhost
  database: furima-46486_test

production:
  <<: *default
  adapter: postgresql
  url: <%= ENV['DATABASE_URL'] %>